# Generated by Django 5.2.5 on 2025-12-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='myapp_booki_user_id_16e4d8_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['event', 'status'], name='myapp_booki_event_i_533ea7_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_date'], name='myapp_booki_booking_63c2cf_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['is_paid', 'status'], name='myapp_booki_is_paid_c76ae2_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['slug'], name='myapp_event_slug_464399_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_active', 'start_date', 'city'], name='myapp_event_is_acti_edde8c_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_featured', 'is_active'], name='myapp_event_is_feat_1ff167_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['host', 'is_active'], name='myapp_event_host_id_606562_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user', '-created_at'], name='myapp_favor_user_id_dee1b1_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['event'], name='myapp_favor_event_i_6b597a_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['event', '-created_at'], name='myapp_revie_event_i_b9661e_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', '-created_at'], name='myapp_revie_user_id_4d0976_idx'),
        ),
    ]
